version: '3'

networks:
  backend:

volumes:
  pgdata:

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
    - 9411:9411
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
      - backend
